### ISSUE TITLE
Please tag the 0.9.0 release of this cookbook

### ISSUE THREAD

**Issue by eherot** [hipsnip-cookbooks/jetty#11]

**Comment by lbdremy** [comment]
Hey @motns you probably have the tag in your local git repo could you push it, please?

**Comment by lbdremy** [comment]
Oh actually it's there under 0.9.0 instead of v0.9.0, I think.

**Comment by eherot** [comment]
Ah I see it there.  Are you transitioning to no-v-tags?  Because I thought most chef stuff was going the other way...

**Comment by motns** [comment]
Yes, good point. For all of our internal projects we've moved to "non-v-tags", just to make life a bit easier in terms of managing builds and dependencies. However, as you pointed out, other cookbooks are indeed using "v-tags", so we should definitely stick to that convention for our cookbooks.
I've now tagged the "0.9.0" release as "v0.9.0" as well, so you should be able to use it.

**Comment by eherot** [comment]
:thumbsup:
