### ISSUE TITLE
`sudo service jetty start` didn't work on CentOS 6.5

### ISSUE THREAD

**Issue by SaitoWu** [hipsnip-cookbooks/jetty#9]
It didn't start the jetty service, and return `started`

but `sudo service jetty run` works.

**Comment by SaitoWu** [comment]
I just figured it out..

It's because my `/etc/default/jetty` has a wrong `JAVA_HOME`config.

So, close...

**Comment by lbdremy** [comment]
Ok thanks @SaitoWu, sorry for the delay of response. Happy you figured out your issue :)
